package jcsgomain;

import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.InputStreamReader;
import java.nio.file.FileSystems;
import javax.swing.JTextPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author martin
 */
public class jCSGO extends javax.swing.JFrame {

    Font FONT_NOTOSANS_PLAIN_12 = new Font("notosans", Font.PLAIN, 12);
    Font FONT_NOTOSANS_BOLD_12 = new Font("notosans", Font.BOLD, 12);
    Font FONT_NOTOSANS_ITALIC_12 = new Font("notosans", Font.ITALIC, 12);
    Font FONT_NOTOSANS_BOLD_ITALIC_12 = new Font("notosans", Font.BOLD + Font.ITALIC, 12);

    /**
     * Creates new form jCSGO
     */
    public jCSGO() {
        initComponents();
        setup();
    }

    public void setup() {
        IOcommunications io = new IOcommunications();
        txtDefaultFolder.setText(io.getDefaultFolder());

        displayFormatedText(txtPane, io.getDefaultFolder() + "\n", FONT_NOTOSANS_BOLD_12, Color.RED);
        for (String maps : io.readFile(io.getDefaultFolder() + "/"
                + "serverfiles/csgo/maplist.txt")) {
            txtMapList.append(maps + "\n");
            comboDefaultMap.addItem(maps);
        }
        for (String map : io.readFile("/home/steam/LinuxGSM-master/serverfiles/csgo/mapcycle.txt")) {
            txtMapcycle.append(map + "\n");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        txtMapcycle1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtDefaultFolder = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnRestartServer = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMapcycle = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnArmsRace = new javax.swing.JButton();
        btnClassicCasual = new javax.swing.JButton();
        btnClassicCompetitive = new javax.swing.JButton();
        btnDeathmatch = new javax.swing.JButton();
        btnDemolition = new javax.swing.JButton();
        btnWingman = new javax.swing.JButton();
        btnCustom = new javax.swing.JButton();
        btnStartServer = new javax.swing.JButton();
        comboDefaultMap = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtMapList = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        btnUseSelected = new javax.swing.JButton();
        btnDeleteSelected = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnClearTextArea = new javax.swing.JButton();
        txtIPaddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPane = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        txtServerName = new javax.swing.JTextField();
        jMenuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuFileExit = new javax.swing.JMenuItem();
        menuServer = new javax.swing.JMenu();
        menuServerDetails = new javax.swing.JMenuItem();
        menuServerServerconfig = new javax.swing.JMenuItem();
        menuServerMaplist = new javax.swing.JMenuItem();
        menuServerMapcycle = new javax.swing.JMenuItem();

        txtMapcycle1.setColumns(20);
        txtMapcycle1.setRows(5);
        jScrollPane4.setViewportView(txtMapcycle1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("IP address:");

        txtDefaultFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDefaultFolderActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel2.setText("jCSGO");

        btnRestartServer.setFont(new java.awt.Font("Noto Mono", 0, 36)); // NOI18N
        btnRestartServer.setText("Restart");
        btnRestartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartServerActionPerformed(evt);
            }
        });

        txtMapcycle.setColumns(20);
        txtMapcycle.setRows(5);
        jScrollPane3.setViewportView(txtMapcycle);

        jLabel3.setText("MapCycle");

        jToolBar1.setRollover(true);

        btnArmsRace.setText("Arms Race");
        btnArmsRace.setFocusable(false);
        btnArmsRace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnArmsRace.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnArmsRace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArmsRaceActionPerformed(evt);
            }
        });
        jToolBar1.add(btnArmsRace);

        btnClassicCasual.setText("Casual");
        btnClassicCasual.setFocusable(false);
        btnClassicCasual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClassicCasual.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClassicCasual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassicCasualActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClassicCasual);

        btnClassicCompetitive.setText("Competitive");
        btnClassicCompetitive.setFocusable(false);
        btnClassicCompetitive.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClassicCompetitive.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClassicCompetitive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassicCompetitiveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClassicCompetitive);

        btnDeathmatch.setText("Deathmatch");
        btnDeathmatch.setFocusable(false);
        btnDeathmatch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeathmatch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeathmatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeathmatchActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDeathmatch);

        btnDemolition.setText("Demolition");
        btnDemolition.setFocusable(false);
        btnDemolition.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDemolition.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDemolition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemolitionActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDemolition);

        btnWingman.setText("Wingman");
        btnWingman.setFocusable(false);
        btnWingman.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnWingman.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnWingman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWingmanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnWingman);

        btnCustom.setText("Custom");
        btnCustom.setFocusable(false);
        btnCustom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCustom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCustom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCustom);

        btnStartServer.setFont(new java.awt.Font("Noto Mono", 0, 18)); // NOI18N
        btnStartServer.setText("Start server");
        btnStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartServerActionPerformed(evt);
            }
        });

        comboDefaultMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDefaultMapActionPerformed(evt);
            }
        });

        txtMapList.setColumns(20);
        txtMapList.setRows(5);
        jScrollPane5.setViewportView(txtMapList);

        jLabel4.setText("MapList");

        btnUseSelected.setText("Use Selected");
        btnUseSelected.setOpaque(true);

        btnDeleteSelected.setText("Delete Selected");
        btnDeleteSelected.setOpaque(true);

        jLabel5.setText("Default map");

        btnClearTextArea.setText("Clear");
        btnClearTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearTextAreaActionPerformed(evt);
            }
        });

        txtIPaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPaddressActionPerformed(evt);
            }
        });

        jLabel6.setText("Default server folder:");

        jScrollPane2.setViewportView(txtPane);

        jLabel7.setText("Server Name:");

        txtServerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServerNameActionPerformed(evt);
            }
        });

        menuFile.setText("File");

        menuFileExit.setText("Exit");
        menuFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileExitActionPerformed(evt);
            }
        });
        menuFile.add(menuFileExit);

        jMenuBar.add(menuFile);

        menuServer.setText("Server");

        menuServerDetails.setText("Details");
        menuServerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServerDetailsActionPerformed(evt);
            }
        });
        menuServer.add(menuServerDetails);

        menuServerServerconfig.setText("Server config");
        menuServerServerconfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServerServerconfigActionPerformed(evt);
            }
        });
        menuServer.add(menuServerServerconfig);

        menuServerMaplist.setText("Maplist");
        menuServerMaplist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServerMaplistActionPerformed(evt);
            }
        });
        menuServer.add(menuServerMaplist);

        menuServerMapcycle.setText("Mapcycle");
        menuServerMapcycle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServerMapcycleActionPerformed(evt);
            }
        });
        menuServer.add(menuServerMapcycle);

        jMenuBar.add(menuServer);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(btnStartServer, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(txtDefaultFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(txtIPaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(txtServerName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(69, 69, 69)
                                        .addComponent(btnRestartServer))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(comboDefaultMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGap(592, 592, 592)
                                        .addComponent(btnClearTextArea)))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnUseSelected)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(154, 154, 154)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnDeleteSelected)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(141, 141, 141))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDeleteSelected, btnUseSelected});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUseSelected)
                            .addComponent(btnDeleteSelected)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnRestartServer)
                                        .addComponent(btnStartServer, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(btnClearTextArea))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(1, 1, 1)
                                                .addComponent(txtServerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(1, 1, 1)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtIPaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtDefaultFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(1, 1, 1)
                                                .addComponent(comboDefaultMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDefaultFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDefaultFolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDefaultFolderActionPerformed

    private void btnRestartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartServerActionPerformed
        process("/home/steam/LinuxGSM-master/csgoserver restart", FONT_NOTOSANS_PLAIN_12, Color.BLACK);
        process("/home/steam/LinuxGSM-master/startcsgo.sh", FONT_NOTOSANS_PLAIN_12, Color.BLACK);
    }//GEN-LAST:event_btnRestartServerActionPerformed

    private void menuServerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServerDetailsActionPerformed
        process("/home/steam/LinuxGSM-master/csgoserver details", FONT_NOTOSANS_PLAIN_12, Color.BLACK);
    }//GEN-LAST:event_menuServerDetailsActionPerformed

    private void menuFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuFileExitActionPerformed

    private void menuServerServerconfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServerServerconfigActionPerformed
        processFile("/home/steam/LinuxGSM-master/serverfiles/csgo/cfg/csgoserver.cfg", FONT_NOTOSANS_PLAIN_12, Color.BLACK);
    }//GEN-LAST:event_menuServerServerconfigActionPerformed

    private void menuServerMaplistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServerMaplistActionPerformed
        processFile("/home/steam/LinuxGSM-master/serverfiles/csgo/maplist.txt", FONT_NOTOSANS_PLAIN_12, Color.BLACK);
    }//GEN-LAST:event_menuServerMaplistActionPerformed

    private void menuServerMapcycleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServerMapcycleActionPerformed
        processFile("/home/steam/LinuxGSM-master/serverfiles/csgo/mapcycle.txt", FONT_NOTOSANS_PLAIN_12, Color.BLACK);
    }//GEN-LAST:event_menuServerMapcycleActionPerformed

    private void btnDemolitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemolitionActionPerformed
        IOcommunications io = new IOcommunications();
        String str = io.getDefaultFolder() + File.separator
                + FileSystems.getDefault().getPath("lgsm", "config-lgsm", "csgoserver", "csgoserver.cfg");
        io.replaceSelected(str, "gametype", "1");
        io.replaceSelected(str, "gamemode", "1");

        displayFormatedText(txtPane, "Changing gamemode to ",
                FONT_NOTOSANS_PLAIN_12, Color.BLACK);
        displayFormatedText(txtPane, "Demolition", FONT_NOTOSANS_PLAIN_12, Color.RED);
        displayFormatedText(txtPane, ". Remember to restart server!!\n",
                FONT_NOTOSANS_PLAIN_12, Color.BLACK);
    }//GEN-LAST:event_btnDemolitionActionPerformed

    private void btnStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartServerActionPerformed
        process("/home/steam/LinuxGSM-master/csgoserver start", FONT_NOTOSANS_PLAIN_12, Color.BLACK);
        process("/home/steam/LinuxGSM-master/startcsgo.sh", FONT_NOTOSANS_PLAIN_12, Color.BLACK);
    }//GEN-LAST:event_btnStartServerActionPerformed

    private void btnArmsRaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArmsRaceActionPerformed
        IOcommunications io = new IOcommunications();
        String str = io.getDefaultFolder() + File.separator
                + FileSystems.getDefault().getPath("lgsm", "config-lgsm", "csgoserver", "csgoserver.cfg");
        io.replaceSelected(str, "gametype", "1");
        io.replaceSelected(str, "gamemode", "0");

        displayFormatedText(txtPane, "Changing gamemode to ",
                FONT_NOTOSANS_PLAIN_12, Color.BLACK);
        displayFormatedText(txtPane, "ArmsRace", FONT_NOTOSANS_PLAIN_12, Color.RED);
        displayFormatedText(txtPane, ". Remember to restart server!!\n",
                FONT_NOTOSANS_PLAIN_12, Color.BLACK);
    }//GEN-LAST:event_btnArmsRaceActionPerformed

    private void btnClassicCasualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassicCasualActionPerformed
        IOcommunications io = new IOcommunications();
        String str = io.getDefaultFolder() + File.separator
                + FileSystems.getDefault().getPath("lgsm", "config-lgsm", "csgoserver", "csgoserver.cfg");
        io.replaceSelected(str, "gametype", "0");
        io.replaceSelected(str, "gamemode", "0");

        displayFormatedText(txtPane, "Changing gamemode to ",
                FONT_NOTOSANS_PLAIN_12, Color.BLACK);
        displayFormatedText(txtPane, "Casual", FONT_NOTOSANS_PLAIN_12, Color.RED);
        displayFormatedText(txtPane, ". Remember to restart server!!\n",
                FONT_NOTOSANS_PLAIN_12, Color.BLACK);
    }//GEN-LAST:event_btnClassicCasualActionPerformed

    private void btnDeathmatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeathmatchActionPerformed
        IOcommunications io = new IOcommunications();
        String str = io.getDefaultFolder() + File.separator
                + FileSystems.getDefault().getPath("lgsm", "config-lgsm", "csgoserver", "csgoserver.cfg");
        io.replaceSelected(str, "gametype", "1");
        io.replaceSelected(str, "gamemode", "2");

        displayFormatedText(txtPane, "Changing gamemode to ",
                FONT_NOTOSANS_PLAIN_12, Color.BLACK);
        displayFormatedText(txtPane, "Deathmatch", FONT_NOTOSANS_PLAIN_12, Color.RED);
        displayFormatedText(txtPane, ". Remember to restart server!!\n",
                FONT_NOTOSANS_PLAIN_12, Color.BLACK);
    }//GEN-LAST:event_btnDeathmatchActionPerformed

    private void btnClassicCompetitiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassicCompetitiveActionPerformed
        IOcommunications io = new IOcommunications();
        String str = io.getDefaultFolder() + File.separator
                + FileSystems.getDefault().getPath("lgsm", "config-lgsm", "csgoserver", "csgoserver.cfg");
        io.replaceSelected(str, "gametype", "0");
        io.replaceSelected(str, "gamemode", "1");

        displayFormatedText(txtPane, "Changing gamemode to ",
                FONT_NOTOSANS_PLAIN_12, Color.BLACK);
        displayFormatedText(txtPane, "Competitive", FONT_NOTOSANS_PLAIN_12, Color.RED);
        displayFormatedText(txtPane, ". Remember to restart server!!\n",
                FONT_NOTOSANS_PLAIN_12, Color.BLACK);
    }//GEN-LAST:event_btnClassicCompetitiveActionPerformed

    private void btnCustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomActionPerformed
        IOcommunications io = new IOcommunications();
        String str = io.getDefaultFolder() + File.separator
                + FileSystems.getDefault().getPath("lgsm", "config-lgsm", "csgoserver", "csgoserver.cfg");
        io.replaceSelected(str, "gametype", "3");
        io.replaceSelected(str, "gamemode", "0");

        displayFormatedText(txtPane, "Changing gamemode to ",
                FONT_NOTOSANS_PLAIN_12, Color.BLACK);
        displayFormatedText(txtPane, "Custom", FONT_NOTOSANS_PLAIN_12, Color.RED);
        displayFormatedText(txtPane, ". Remember to restart server!!\n",
                FONT_NOTOSANS_PLAIN_12, Color.BLACK);
    }//GEN-LAST:event_btnCustomActionPerformed

    private void btnWingmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWingmanActionPerformed
        IOcommunications io = new IOcommunications();
        String str = io.getDefaultFolder() + File.separator
                + FileSystems.getDefault().getPath("lgsm", "config-lgsm", "csgoserver", "csgoserver.cfg");
        io.replaceSelected(str, "gametype", "0");
        io.replaceSelected(str, "gamemode", "2");

        displayFormatedText(txtPane, "Changing gamemode to ",
                FONT_NOTOSANS_PLAIN_12, Color.BLACK);
        displayFormatedText(txtPane, "Wingman", FONT_NOTOSANS_PLAIN_12, Color.RED);
        displayFormatedText(txtPane, ". Remember to restart server!!\n",
                FONT_NOTOSANS_PLAIN_12, Color.BLACK);
    }//GEN-LAST:event_btnWingmanActionPerformed

    private void comboDefaultMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDefaultMapActionPerformed
        IOcommunications io = new IOcommunications();
        String str = io.getDefaultFolder() + File.separator
                + FileSystems.getDefault().getPath("lgsm", "config-lgsm", "csgoserver", "csgoserver.cfg");
        String map = comboDefaultMap.getSelectedItem().toString();
        io.replaceSelected(str, "defaultmap", map);

        displayFormatedText(txtPane, "Changing  ",
                FONT_NOTOSANS_PLAIN_12, Color.BLACK);
        displayFormatedText(txtPane, "defaultmap",
                FONT_NOTOSANS_BOLD_12, Color.BLACK);
        displayFormatedText(txtPane, " to ",
                FONT_NOTOSANS_PLAIN_12, Color.BLACK);
        displayFormatedText(txtPane, map, FONT_NOTOSANS_PLAIN_12, Color.RED);
        displayFormatedText(txtPane, ". Remember to restart server!!\n",
                FONT_NOTOSANS_PLAIN_12, Color.BLACK);

    }//GEN-LAST:event_comboDefaultMapActionPerformed

    private void btnClearTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearTextAreaActionPerformed
        txtPane.setText("");
    }//GEN-LAST:event_btnClearTextAreaActionPerformed

    private void txtIPaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPaddressActionPerformed

    private void txtServerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServerNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jCSGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jCSGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jCSGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jCSGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jCSGO().setVisible(true);
            }
        });
    }

    public void process(String command, Font font, Color color) {
        String s;
        Process p;
        BufferedReader br = null;
        try {
            displayFormatedText(txtPane, command + "\n", font, color);
            p = Runtime.getRuntime().exec(command);
            br = new BufferedReader(
                    new InputStreamReader(p.getInputStream()));

            while ((s = br.readLine()) != null) {
                s = s.trim();
                s = s.replace("[K[ .... ] ", "");
                s = s.replace("[36m INFO", "");
                s = s.replace("[K[ ", "");
                String[] ip = s.split("csgoserver:");
                try {
                    // removing special formating from bash script
                    s = s.replace("[0m", "");
                    if (ip[1].trim().startsWith("Check IP: ")) {
                        txtIPaddress.setText(ip[1].substring(10));
                    }
                } catch (Exception ex) {
                }
                if (s.contains("[93m") || s.contains("[92m")) {
                    s = s.replace("[93m", "");
                    s = s.replace("[92m", "");
                    displayFormatedText(txtPane, s + "\n", FONT_NOTOSANS_BOLD_12, Color.BLUE);
                } else if (s.contains("[34m") || s.contains("[32m")) {
                    s = s.replace("[34m", "");
                    s = s.replace("[32m", "");
                    displayFormatedText(txtPane, s + "\n", font, color);
                } else {
                    displayFormatedText(txtPane, s + "\n", font, color);
                }
            }
            p.waitFor();
            p.destroy();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void processFile(String file, Font font, Color color) {
        String s;
        File f;
        BufferedReader br = null;
        try {
            displayFormatedText(txtPane, "Reading file: ", font, color);
            displayFormatedText(txtPane, file + "\n", FONT_NOTOSANS_ITALIC_12, color);
            f = new File(file);
            br = new BufferedReader(new FileReader(f));

            while ((s = br.readLine()) != null) {
                if (s.startsWith("//")) {
                    displayFormatedText(txtPane, s + "\n", FONT_NOTOSANS_BOLD_12, Color.BLUE);
                } else {
                    displayFormatedText(txtPane, s + "\n", font, color);
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArmsRace;
    private javax.swing.JButton btnClassicCasual;
    private javax.swing.JButton btnClassicCompetitive;
    private javax.swing.JButton btnClearTextArea;
    private javax.swing.JButton btnCustom;
    private javax.swing.JButton btnDeathmatch;
    private javax.swing.JButton btnDeleteSelected;
    private javax.swing.JButton btnDemolition;
    private javax.swing.JButton btnRestartServer;
    private javax.swing.JButton btnStartServer;
    private javax.swing.JButton btnUseSelected;
    private javax.swing.JButton btnWingman;
    private javax.swing.JComboBox<String> comboDefaultMap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuFileExit;
    private javax.swing.JMenu menuServer;
    private javax.swing.JMenuItem menuServerDetails;
    private javax.swing.JMenuItem menuServerMapcycle;
    private javax.swing.JMenuItem menuServerMaplist;
    private javax.swing.JMenuItem menuServerServerconfig;
    private javax.swing.JTextField txtDefaultFolder;
    private javax.swing.JTextField txtIPaddress;
    private javax.swing.JTextArea txtMapList;
    private javax.swing.JTextArea txtMapcycle;
    private javax.swing.JTextArea txtMapcycle1;
    private javax.swing.JTextPane txtPane;
    private javax.swing.JTextField txtServerName;
    // End of variables declaration//GEN-END:variables

    public void displayFormatedText(JTextPane tp, String txt, Font font, Color color) {

        StyledDocument doc = (StyledDocument) tp.getDocument();
        try {

            doc.insertString(doc.getLength(), txt, displayFormat(font, color));

        } catch (BadLocationException ex) {
            System.out.println(ex);
        }

    }

    public SimpleAttributeSet displayFormat(Font font, Color color) {
//        Font trb_18 = new Font("TimesRoman", Font.BOLD, 18);
//        Font tri = new Font("TimesRoman", Font.ITALIC, 18);
//        Font times_b_i = new Font("TimesRoman", Font.BOLD + Font.ITALIC, 18);
//        Font h = new Font("Helvetica", Font.PLAIN, 18);
//        Font c = new Font("Courier", Font.PLAIN, 18);
//        Font d = new Font("Dialog", Font.PLAIN, 18);
//        Font z = new Font("ZapfDingbats", Font.PLAIN, 18);
        SimpleAttributeSet sAS = new SimpleAttributeSet();

        StyleConstants.setFontFamily(sAS, font.getFamily());
        StyleConstants.setFontSize(sAS, font.getSize());
        StyleConstants.setBold(sAS, font.isBold());
        StyleConstants.setItalic(sAS, font.isItalic());
        StyleConstants.setForeground(sAS, color);

        return sAS;
    }

}
